# Generated by Django 3.1.3 on 2021-02-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210219_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='questions.question'),
        ),
    ]
