# Generated by Django 3.1.3 on 2020-11-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201115_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
