# Generated by Django 3.1.3 on 2021-02-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
